### ISSUE TITLE
AssertionError in Evaluation

### ISSUE THREAD

**Issue by yzrs** [xuzhang1199/CLAMP#5]
Hi,thanks for your contribution.When I use this command to **evaluate the pretrained model**, I meet the some errors. 
`bash tools/dist_test.sh configs/animal/2d_kpt_sview_rgb_img/topdown_heatmap/ap10k/CLAMP_ViTB_ap10k_256x256.py work_dirs/CLAMP_ViTB_ap10k_256x256/epoch_210.pth 2 "0,1"`

**Errors are follows:**
>  /home/administrator/Desktop/zy/CLAMP/mmcv/mmcv/cnn/bricks/transformer.py:28: UserWarning: Fail to import ``MultiScaleDeformableAttention`` from ``mmcv.ops.multi_scale_deform_attn``, You should install ``mmcv-full`` if you need this module. 
  warnings.warn('Fail to import ``MultiScaleDeformableAttention`` from '
Traceback (most recent call last):
  File "tools/test.py", line 174, in <module>
    main()
  File "tools/test.py", line 156, in main
    outputs = multi_gpu_test(model, data_loader, args.tmpdir,
  File "/home/administrator/Desktop/zy/CLAMP/mmpose/apis/test.py", line 70, in multi_gpu_test
    result = model(return_loss=False, **data)
  File "/home/administrator/miniconda3/envs/clamp/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/administrator/miniconda3/envs/clamp/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1040, in forward
    output = self._run_ddp_forward(*inputs, **kwargs)
  File "/home/administrator/miniconda3/envs/clamp/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1000, in _run_ddp_forward
    return module_to_run(*inputs[0], **kwargs[0])
  File "/home/administrator/miniconda3/envs/clamp/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/administrator/Desktop/zy/CLAMP/mmcv/mmcv/runner/fp16_utils.py", line 98, in new_func
    return old_func(*args, **kwargs)
  File "/home/administrator/Desktop/zy/CLAMP/mmpose/models/detectors/top_down.py", line 448, in forward
    return self.forward_test(
  File "/home/administrator/Desktop/zy/CLAMP/mmpose/models/detectors/top_down.py", line 545, in forward_test
    assert img.size(0) == len(img_metas)
AssertionError

**Here the img.size(0) is 32 while the length of img_metas is 1, so I got the AssertionError. What should I do?**

**Comment by xuzhang1199** [comment]
Did you follow the instructions to install related packages? I did not meet such an error.

**Comment by yzrs** [comment]
Of course. I follow the instruction to install mmcv and mmpose.
But when I run **dist_train.sh**, it gives me the AttributeError: ‘**MMDistributedDataParallel**‘ object has no attribute ‘_sync_params‘  . I solve this problem according to [this blog](https://blog.csdn.net/qq_33854260/article/details/129037203 ) . After that everything is OK in training. 
But when I try use **dist_test.sh** to evaluate the pretrained model, it gives me the AssertionError above. My cuda version is 11.4 and my pytorch version is 1.13.1

**Comment by xuzhang1199** [comment]
I did not test my code on torch 1.13. You may have a try on lower versions, such as torch 1.7 1.8.

**Comment by Liufanye** [comment]
> I did not test my code on torch 1.13. You may have a try on lower versions, such as torch 1.7 1.8.

I think what you said is correct. If the version of torch is too high, problems will arise.
