### ISSUE TITLE
RuntimeError and AssertionError

### ISSUE THREAD

**Issue by Nothingf** [xuzhang1199/CLAMP#7]
**Thanks for your contribution!** When I use these commands to train the model,  I meet the some errors.
`bash tools/dist_train.sh configs/animal/2d_kpt_sview_rgb_img/topdown_heatmap/ap10k/CLAMP_ViTB_ap10k_256x256.py 1 "1"`
`bash tools/dist_train.sh configs/animal/2d_kpt_sview_rgb_img/topdown_heatmap/ap10k/CLAMP_ViTB_ap10k_256x256.py 2 "0,1"`

**When I trained 10 epochs after running the commands, the following error occurred:**

> 2023-12-23 17:53:35,495 - mmpose - INFO - Saving checkpoint at 10 epochs
[                                                  ] 0/1272, elapsed: 0s, ETA:/data2/liuyf/CLAMP/mmcv/mmcv/cnn/bricks/transformer.py:28: UserWarning: Fail to import ``MultiScaleDeformableAttention`` from ``mmcv.ops.multi_scale_deform_attn``, You should install ``mmcv-full`` if you need this module. 
  warnings.warn('Fail to import ``MultiScaleDeformableAttention`` from '
/data2/liuyf/CLAMP/mmcv/mmcv/cnn/bricks/transformer.py:28: UserWarning: Fail to import ``MultiScaleDeformableAttention`` from ``mmcv.ops.multi_scale_deform_attn``, You should install ``mmcv-full`` if you need this module. 
  warnings.warn('Fail to import ``MultiScaleDeformableAttention`` from '
/data2/liuyf/CLAMP/mmcv/mmcv/cnn/bricks/transformer.py:28: UserWarning: Fail to import ``MultiScaleDeformableAttention`` from ``mmcv.ops.multi_scale_deform_attn``, You should install ``mmcv-full`` if you need this module. 
  warnings.warn('Fail to import ``MultiScaleDeformableAttention`` from '
/data2/liuyf/CLAMP/mmcv/mmcv/cnn/bricks/transformer.py:28: UserWarning: Fail to import ``MultiScaleDeformableAttention`` from ``mmcv.ops.multi_scale_deform_attn``, You should install ``mmcv-full`` if you need this module. 
  warnings.warn('Fail to import ``MultiScaleDeformableAttention`` from '
terminate called without an active exception
terminate called without an active exception
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f9ad6d677a0>
Traceback (most recent call last):
  File "/data2/liuyf/anaconda3/envs/clamp/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1466, in __del__
    self._shutdown_workers()
  File "/data2/liuyf/anaconda3/envs/clamp/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1430, in _shutdown_workers
    w.join(timeout=_utils.MP_STATUS_CHECK_INTERVAL)
  File "/data2/liuyf/anaconda3/envs/clamp/lib/python3.7/multiprocessing/process.py", line 140, in join
    res = self._popen.wait(timeout)
  File "/data2/liuyf/anaconda3/envs/clamp/lib/python3.7/multiprocessing/popen_fork.py", line 45, in wait
    if not wait([self.sentinel], timeout):
  File "/data2/liuyf/anaconda3/envs/clamp/lib/python3.7/multiprocessing/connection.py", line 921, in wait
    ready = selector.select(timeout)
  File "/data2/liuyf/anaconda3/envs/clamp/lib/python3.7/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
  File "/data2/liuyf/anaconda3/envs/clamp/lib/python3.7/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 4149941) is killed by signal: Aborted. 
Traceback (most recent call last):
  File "tools/train.py", line 174, in <module>
    main()
  File "tools/train.py", line 170, in main
    meta=meta)
  File "/data2/liuyf/CLAMP/mmpose/apis/train.py", line 193, in train_model
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/data2/liuyf/CLAMP/mmcv/mmcv/runner/epoch_based_runner.py", line 130, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/data2/liuyf/CLAMP/mmcv/mmcv/runner/epoch_based_runner.py", line 57, in train
    self.call_hook('after_train_epoch')
  File "/data2/liuyf/CLAMP/mmcv/mmcv/runner/base_runner.py", line 307, in call_hook
    getattr(hook, fn_name)(self)
  File "/data2/liuyf/CLAMP/mmcv/mmcv/runner/hooks/evaluation.py", line 267, in after_train_epoch
    self._do_evaluate(runner)
  File "/data2/liuyf/CLAMP/mmcv/mmcv/runner/hooks/evaluation.py", line 501, in _do_evaluate
    gpu_collect=self.gpu_collect)
  File "/data2/liuyf/CLAMP/mmpose/apis/test.py", line 70, in multi_gpu_test
    result = model(return_loss=False, **data)
  File "/data2/liuyf/anaconda3/envs/clamp/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data2/liuyf/anaconda3/envs/clamp/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 1040, in forward
    output = self._run_ddp_forward(*inputs, **kwargs)
  File "/data2/liuyf/anaconda3/envs/clamp/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 1000, in _run_ddp_forward
    return module_to_run(*inputs[0], **kwargs[0])
  File "/data2/liuyf/anaconda3/envs/clamp/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data2/liuyf/CLAMP/mmcv/mmcv/runner/fp16_utils.py", line 98, in new_func
    return old_func(*args, **kwargs)
  File "/data2/liuyf/CLAMP/mmpose/models/detectors/top_down.py", line 449, in forward
    img, img_metas, return_heatmap=return_heatmap, **kwargs)
  File "/data2/liuyf/CLAMP/mmpose/models/detectors/top_down.py", line 545, in forward_test
    assert img.size(0) == len(img_metas)
AssertionError
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 4126250) of binary: /data2/liuyf/anaconda3/envs/clamp/bin/python
Traceback (most recent call last):
  File "/data2/liuyf/anaconda3/envs/clamp/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/data2/liuyf/anaconda3/envs/clamp/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/data2/liuyf/anaconda3/envs/clamp/lib/python3.7/site-packages/torch/distributed/launch.py", line 195, in <module>
    main()
  File "/data2/liuyf/anaconda3/envs/clamp/lib/python3.7/site-packages/torch/distributed/launch.py", line 191, in main
    launch(args)
  File "/data2/liuyf/anaconda3/envs/clamp/lib/python3.7/site-packages/torch/distributed/launch.py", line 176, in launch
    run(args)
  File "/data2/liuyf/anaconda3/envs/clamp/lib/python3.7/site-packages/torch/distributed/run.py", line 756, in run
    )(*cmd_args)
  File "/data2/liuyf/anaconda3/envs/clamp/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/data2/liuyf/anaconda3/envs/clamp/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 248, in launch_agent
    failures=result.failures,
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
tools/train.py FAILED
------------------------------------------------------------

Failures:

  <NO_OTHER_FAILURES>
------------------------------------------------------------

Root Cause (first observed failure):

[0]:
  time      : 2023-12-23_17:54:20
  host      : cggi
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 4126250)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

 **What should I do?**

**Comment by xuzhang1199** [comment]
I did not meet such errors. I would like to remind you that this repo has already included mmcv. If you install mmcv otherwise, there will be some errors.

**Comment by Liufanye** [comment]
Hello, do you encounter the situation where the accuracy collapses to 0 when using two cards for training?
